packages:
  - apps/*
  - packages/*

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: false

catalog:
  '@eslint/js': 10.0.1
  '@fastify/cookie': 11.1.2
  '@nestjs/common': 12.1.2
  '@nestjs/core': 12.1.2
  '@nestjs/platform-fastify': 12.1.2
  '@nestjs/swagger': 12.0.2
  '@nestjs/testing': 12.1.2
  '@node-rs/argon2': 2.2.2
  '@testing-library/jest-dom': 7.0.1
  '@testing-library/react': 16.3.3
  '@types/node': 26.6.4
  '@types/nodemailer': 8.0.2
  '@types/pg': 8.23.1
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  '@types/smtp-server': 3.5.13
  '@vitejs/plugin-react': 6.1.2
  bullmq: 6.3.11
  eslint: 10.12.0
  eslint-plugin-react-hooks: 7.1.1
  eslint-plugin-react-refresh: 0.5.7
  fastify: 5.12.5
  globals: 17.13.0
  jsdom: 30.1.2
  nodemailer: 10.0.15
  pg: 8.23.1
  pino: 10.4.0
  prettier: 3.9.9
  react: 19.3.0
  react-dom: 19.3.0
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  smtp-server: 3.19.17
  tsx: 4.23.15
  typescript: 6.0.3
  typescript-eslint: 8.71.1
  uuid: 14.0.2
  vite: 8.3.3
  vitest: 5.0.3
  zod: 4.6.5

catalogMode: strict

cleanupUnusedCatalogs: true

injectWorkspacePackages: true

linkWorkspacePackages: true
